### ISSUE TITLE
Tensorflow 2.1.0 Issue

### ISSUE THREAD

**Issue by Jaesung-Jun** [Guillem96/efficientdet-tf#10]
I just run command;
$pip install git+https://github.com/Guillem96/efficientdet-tf
and it installed without errors.

but I had an error;
```bash
(EfficientDetTF2) F:\Github Repos\Darksouls3-RL\object_detection\efficientdet>python -m efficientdet.train --efficientdet 0 --bidirectional --no-freeze-backbone --format labelme --train-dataset ../Gundyr_labeled --images-path ../Gundyr_labeled --classes-names gundyr --n-classes 1 --epochs 100 --batch-size 8 --w-scheduler --learning-rate 1e-2 --grad-accum-steps 2 --save-dir ../models/
C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "F:\Anaconda\envs\EfficientDetTF2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Anaconda\envs\EfficientDetTF2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Anaconda\envs\EfficientDetTF2\lib\site-packages\efficientdet\train.py", line 10, in <module>
    import efficientdet.engine as engine
  File "F:\Anaconda\envs\EfficientDetTF2\lib\site-packages\efficientdet\engine.py", line 51, in <module>
    print_every: int = 10):
  File "C:\Users\Jae-sung Jun\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'optimizers'
```

I fixed this error to downgrade Tensorflow 2.1.0 => 2.0.0
run this command
```bash
$ pip install tensorflow==2.0.0
```

**Comment by Guillem96** [comment]
I should use the keras namespace. Thanks for the feedback I really appreciate it

**Comment by Jaesung-Jun** [comment]
> I should use the keras namespace. Thanks for the feedback I really appreciate it

Thx for your reply :) Have a nice day
